[features]
seeds = false
skip-lint = false
[programs.localnet]
dominari = "3YdayPtujByJ1g1DWEUh7vpg78gZL49FWyD5rDGyof9T"
registry = "H5mieGWWK6qukHoNzbR6ysLxReeQC4JHZcNM6JkPQnm3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/spacemandev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
