[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dominari-sdk = { path = "../dominari-sdk" }
tokio = { version = "1.23.0", features=["full"]}